# Generated by Django 2.2.7 on 2019-11-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Burgers', '0002_auto_20191114_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name=0),
        ),
    ]
