# Generated by Django 2.2.7 on 2019-11-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Burgers', '0003_auto_20191114_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
