# Generated by Django 2.2.7 on 2019-11-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='tested burger', max_length=100)),
                ('category', models.CharField(default='Burger', max_length=100)),
                ('preparing_time', models.CharField(default='10-15min', max_length=100)),
                ('components', models.CharField(default='one two three four five', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('img', models.ImageField(upload_to='Burgers')),
            ],
        ),
    ]
