# Generated by Django 2.2.7 on 2019-11-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_drink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='tested pizza', max_length=100)),
                ('category', models.CharField(default='Pizza', max_length=100)),
                ('preparing_time', models.CharField(default='10-15min', max_length=100)),
                ('components', models.CharField(default='one two three four five', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('img', models.ImageField(upload_to='Pizza')),
            ],
        ),
    ]
