# Generated by Django 2.2.7 on 2019-12-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0004_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger',
            name='components',
            field=models.CharField(default='one two three four five', max_length=1000),
        ),
    ]
