# Generated by Django 2.2.8 on 2019-12-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0006_auto_20191201_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Product name', max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('preparing_time', models.CharField(default='10-15min', max_length=1000)),
                ('components', models.CharField(default='one two three four five', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
