# Generated by Django 2.2.8 on 2019-12-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0008_auto_20191210_1216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Burger',
        ),
        migrations.DeleteModel(
            name='Dessert',
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
