# Generated by Django 2.2.7 on 2019-11-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Desserts', '0002_auto_20191114_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessert',
            name='description',
            field=models.TextField(default='def', max_length=100),
        ),
    ]
