# Generated by Django 2.2.7 on 2019-11-14 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Desserts', '0003_dessert_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dessert',
            name='description',
        ),
    ]
