# Generated by Django 2.2.7 on 2019-11-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='components',
            field=models.TextField(default='one two three four five'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='description',
            field=models.TextField(default='pizza descr'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='preparing_time',
            field=models.TextField(default='10-15min'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.TextField(default='15$'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.TextField(verbose_name='tested pizza'),
        ),
    ]
