# Generated by Django 2.2.7 on 2019-11-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0002_auto_20191114_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.TextField(default='tested pizza'),
        ),
    ]
