# Generated by Django 2.2.7 on 2019-11-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0003_auto_20191114_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Burgers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(default='pizza descr')),
                ('preparing_time', models.TextField(default='10-15min')),
                ('components', models.TextField(default='one two three four five')),
                ('price', models.TextField(default='15$')),
            ],
        ),
    ]
