# Generated by Django 2.2.7 on 2019-11-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0004_burgers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desserts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='tested dessert')),
                ('description', models.TextField(default='dessert descr')),
                ('preparing_time', models.TextField(default='10-15min')),
                ('components', models.TextField(default='one two three four five')),
                ('price', models.TextField(default='20$')),
            ],
        ),
        migrations.AlterField(
            model_name='burgers',
            name='description',
            field=models.TextField(default='burger descr'),
        ),
        migrations.AlterField(
            model_name='burgers',
            name='name',
            field=models.TextField(default='tested burger'),
        ),
    ]
