# Generated by Django 2.2.7 on 2019-11-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0005_auto_20191114_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='desserts',
            name='components',
            field=models.TextField(default='one two three four five'),
        ),
        migrations.AddField(
            model_name='desserts',
            name='description',
            field=models.TextField(default='dessert descr'),
        ),
        migrations.AddField(
            model_name='desserts',
            name='name',
            field=models.TextField(default='tested dessert'),
        ),
        migrations.AddField(
            model_name='desserts',
            name='preparing_time',
            field=models.TextField(default='10-15min'),
        ),
        migrations.AddField(
            model_name='desserts',
            name='price',
            field=models.TextField(default='20$'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='description',
            field=models.TextField(default='drink descr'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='name',
            field=models.TextField(default='tested drink'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='price',
            field=models.TextField(default='5$'),
        ),
    ]
