# Generated by Django 2.2.7 on 2019-11-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0006_auto_20191114_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='tested burger')),
                ('category', models.TextField(default='Burger')),
                ('preparing_time', models.TextField(default='10-15min')),
                ('components', models.TextField(default='one two three four five')),
                ('price', models.TextField(default='15$')),
            ],
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='tested dessert')),
                ('category', models.TextField(default='Dessert')),
                ('preparing_time', models.TextField(default='10-15min')),
                ('components', models.TextField(default='one two three four five')),
                ('price', models.TextField(default='20$')),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='tested drink')),
                ('category', models.TextField(default='Drink')),
                ('preparing_time', models.TextField(default='10-15min')),
                ('components', models.TextField(default='one two three four five')),
                ('price', models.TextField(default='5$')),
            ],
        ),
        migrations.DeleteModel(
            name='Burgers',
        ),
        migrations.DeleteModel(
            name='Desserts',
        ),
        migrations.DeleteModel(
            name='Drinks',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='description',
        ),
        migrations.AddField(
            model_name='pizza',
            name='category',
            field=models.TextField(default='Pizza'),
        ),
    ]
