# Generated by Django 2.2.7 on 2019-11-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0008_auto_20191114_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger',
            name='category',
            field=models.CharField(default='Burger', max_length=100),
        ),
        migrations.AlterField(
            model_name='burger',
            name='components',
            field=models.CharField(default='one two three four five', max_length=100),
        ),
        migrations.AlterField(
            model_name='burger',
            name='name',
            field=models.CharField(default='tested burger', max_length=100),
        ),
        migrations.AlterField(
            model_name='burger',
            name='preparing_time',
            field=models.CharField(default='10-15min', max_length=100),
        ),
        migrations.AlterField(
            model_name='burger',
            name='price',
            field=models.CharField(default='15$', max_length=100),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='category',
            field=models.CharField(default='Dessert', max_length=100),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='components',
            field=models.CharField(default='one two three four five', max_length=100),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='name',
            field=models.CharField(default='tested dessert', max_length=100),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='preparing_time',
            field=models.CharField(default='10-15min', max_length=100),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='price',
            field=models.CharField(default='20$', max_length=100),
        ),
        migrations.AlterField(
            model_name='drink',
            name='category',
            field=models.CharField(default='Drink', max_length=100),
        ),
        migrations.AlterField(
            model_name='drink',
            name='components',
            field=models.CharField(default='one two three four five', max_length=100),
        ),
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(default='tested drink', max_length=100),
        ),
        migrations.AlterField(
            model_name='drink',
            name='preparing_time',
            field=models.CharField(default='10-15min', max_length=100),
        ),
        migrations.AlterField(
            model_name='drink',
            name='price',
            field=models.CharField(default='5$', max_length=100),
        ),
    ]
