# Generated by Django 2.2.7 on 2019-11-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0009_auto_20191114_1831'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Burger',
        ),
        migrations.DeleteModel(
            name='Dessert',
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
    ]
